# Config for single device full finetuning in full_finetune_single_device.py
# using a Llama3.2 11B Vision Instruct model
#
# This config assumes that you've run the following command before launching:
#   tune download meta-llama/Llama-3.2-11B-Vision-Instruct --output-dir /tmp/Llama-3.2-11B-Vision-Instruct --ignore-patterns "original/consolidated*"
#
# To launch on a single device, run the following command from root:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2_vision/11B_qat_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training:
#    tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2_vision/11B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 11B_full_single_device.yaml for those cases.

output_dir: /tmp/torchtune/llama3_2_vision_11B/qat_full # /tmp may be deleted by your system. Change it to your preference.

# Model arguments
model:
  _component_: torchtune.models.llama3_2_vision.llama3_2_vision_11b
  decoder_trainable: False
  encoder_trainable: True
  fusion_trainable: True
  image_size: 560 # Make sure this matches the image_size in tokenizer

# Transform
tokenizer:
  _component_: torchtune.models.llama3_2_vision.llama3_2_vision_transform
  path: /home/yashkhare/workspace/Llama-3.2-11B-Vision-Instruct/original/tokenizer.model
  image_size: 560
  max_seq_len: 8192

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /home/yashkhare/workspace/Llama-3.2-11B-Vision-Instruct/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00005"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3_VISION
resume_from_checkpoint: False



# Dataset
dataset:
  _component_: torchtune.datasets.custom_sft_dataset
  source: json
  dataset_path: /home/yashkhare/workspace/data/output/all_conversations.json
seed: null
shuffle: True
collate_fn: torchtune.data.padded_collate_tiled_images_and_mask


# Validation
run_val_every_n_steps: 10
dataset_val:
  _component_: torchtune.datasets.custom_sft_dataset
  source: json
  dataset_path: /home/yashkhare/workspace/data/output/val.json
batch_size_val: ${batch_size}


# # Dataset
# dataset:
#   _component_: torchtune.datasets.multimodal.vqa_dataset
#   source: json
#   data_files:
#     train: /home/yashkhare/workspace/medft_data/mimic/vqa_train.json
#   split: train
#   column_map:
#     input: instruction
#     output: output
#     image: image
# seed: null
# shuffle: True
# collate_fn: torchtune.data.padded_collate_tiled_images_and_mask

# # Validation
# # run_val_every_epoch: 1  # Run validation after every epoch
# run_val_every_n_steps: 5
# dataset_val:
#   _component_: torchtune.datasets.multimodal.vqa_dataset
#   source: json
#   data_files:
#     val: /home/yashkhare/workspace/medft_data/mimic/vqa_validation.json
#   split: val
#   column_map:
#     input: instruction
#     output: output
#     image: image
# batch_size_val: ${batch_size}

# Fine-tuning arguments
epochs: 1
save_every_n_steps: 10
max_steps_per_epoch: 100
fake_quant_after_n_steps: 5
memory_efficient_fsdp_wrap: False
batch_size: 4
gradient_accumulation_steps: 8  # Use to increase effective batch size
optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  fused: True
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1

loss:
  _component_: torchtune.modules.loss.LinearCrossEntropyLoss
clip_grad_norm: 1.0
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True  # True reduces memory
custom_sharded_layers: ['decoder.tok_embeddings']  # Layers to shard separately (useful for large vocab size models). Lower Memory, but lower speed.
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.


# QAT arguments
quantizer:
  _component_: torchtune.training.quantization.Int8DynActInt4WeightQATQuantizer
  groupsize: 256


# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
